Setup:
1. copy server-1..3 files into config folder

2. Create a cluster-id

KAFKA_CLUSTER_ID="$(sh kafka-storage.sh random-uuid)"
echo $KAFKA_CLUSTER_ID


3. Format the storage directory (formatting storage,initializing cluster metadata,wiping/resetting broker data)
sh kafka-storage.sh format -t $KAFKA_CLUSTER_ID -c ../config/server-1.properties
sh kafka-storage.sh format -t $KAFKA_CLUSTER_ID -c ../config/server-2.properties
sh kafka-storage.sh format -t $KAFKA_CLUSTER_ID -c ../config/server-3.properties

4. Start 3 kafka servers
sh kafka-server-start.sh ../config/server-1.properties
sh kafka-server-start.sh ../config/server-2.properties
sh kafka-server-start.sh ../config/server-3.properties

5. To get metadata information

sh kafka-metadata-quorum.sh --bootstrap-server localhost:9092  describe --status

sh kafka-metadata-quorum.sh --bootstrap-server localhost:9092  describe  --replication

sh kafka-metadata-quorum.sh --bootstrap-server localhost:9092  describe  --replication --human-readable 

sh kafka-broker-api-versions.sh --bootstrap-server localhost:9092


sh kafka-cluster.sh cluster-id  --bootstrap-server localhost:9092 

6. To create a topic

sh kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 3 --partitions 3 --topic failover

7. To describe a topic

sh kafka-topics.sh --describe --bootstrap-server localhost:9092 --topic failover

8. Dynamically changing the configuration

sh kafka-configs.sh --bootstrap-server localhost:9092 --entity-type topics --entity-name failover --add-config min.insync.replicas=3 --alter









